name: fetch and post price

on:
  schedule:
    - cron: "*/58 * * * *" # 每 58 分钟运行一次
  workflow_dispatch:

# 添加权限设置
permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run crawler
        env:
          GITHUB_ACTIONS: true
        run: python main.py

      - name: Commit and push if changes
        run: |
          git config --global user.name 'harrietlq'
          git config --global user.email 'flashaq@hotmail.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update by GitHub Actions at $(TZ=Asia/Shanghai date)" && git push)
